# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
!pip3 install --upgrade numpy
import numpy as np

You should consider upgrading via the 'C:\Users\ponnu\anacondaponnu\python.exe -m pip install --upgrade pip' command.


#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)

1.21.2


#### 3. Create a null vector of size 10

In [4]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [12]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [5]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [6]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [9]:
arr=np.arange(1,11)
print(arr,end="\n")
a=arr[::-1]
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [21]:
arr=np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [10]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [17]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.0178268  0.60559068 0.75569207]
  [0.54198851 0.16383906 0.16416016]
  [0.02673466 0.52309835 0.01690328]]

 [[0.88832628 0.94130083 0.6828573 ]
  [0.77064249 0.79873014 0.08467603]
  [0.71376623 0.75649093 0.015007  ]]

 [[0.86603608 0.98184052 0.10979521]
  [0.95883559 0.70925693 0.51077862]
  [0.52595668 0.17458277 0.38130572]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
arr=np.random.random((10,10))
print(arr)
print("MAXIMIM VALUE ",np.max(arr))
print("MINIMUM VALUE ",np.min(arr))

[[0.6696878  0.34451904 0.18695653 0.35133514 0.39551552 0.89351725
  0.48431467 0.68663246 0.83429832 0.84957676]
 [0.28017058 0.88303358 0.02269016 0.3821203  0.10934713 0.69107857
  0.23973721 0.16922299 0.01505795 0.03048217]
 [0.09064566 0.44340645 0.31461797 0.60987731 0.29607795 0.8792862
  0.47856241 0.92872204 0.85189442 0.93569884]
 [0.1377603  0.39594052 0.74777417 0.00536853 0.58255018 0.58501622
  0.70491929 0.64067572 0.38027152 0.75047975]
 [0.92983007 0.98820269 0.57676485 0.43705374 0.44704554 0.90630952
  0.29463522 0.1870181  0.01302549 0.76006664]
 [0.0124641  0.28902608 0.27365373 0.59889507 0.57056761 0.69798285
  0.88159426 0.97004738 0.88324269 0.73554075]
 [0.51209246 0.58038513 0.83016313 0.31434867 0.86295295 0.85916653
  0.62110154 0.16791907 0.20477697 0.51349081]
 [0.66095562 0.51806532 0.87681158 0.49823593 0.05223188 0.37025615
  0.16890673 0.03625421 0.01606213 0.15836209]
 [0.80325426 0.16031529 0.42274016 0.14148141 0.66708166 0.90752099
  0.86686098 

#### 14. Create a random vector of size 30 and find the mean value

In [21]:
arr=np.random.random((30))
m=np.mean(arr)
print("MEAN VALUE: ",m)

MEAN VALUE:  0.5052696738981994


#### 15. Create a 2d array with 1 on the border and 0 inside

In [4]:
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [10]:
arr=np.ones((6,6))
arr=np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [7]:

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
z=np.diag(np.arange(4)+1,-1)
print(z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
